# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iY3kDW2QOOn4NDv1zhC91ark_wplQC8m
"""

import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

df.head()

df[
    df['population'] < 500
].median_house_value.mean()

df['population'].min()

df[
    df['population'] == 3.0
] [['households']]